AWSTemplateFormatVersion: '2010-09-09'
Description: 'Infraestructura de Red VPC para Cluster EKS - Innovatech Chile'

Parameters:
  VpcCIDR:
    Type: String
    Default: 10.0.0.0/16
    Description: Rango IP principal para la VPC completa

Resources:
  # 1. La Red Virtual Principal (VPC)
  EKSVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: Innovatech-EKS-VPC

  # 2. La Puerta de enlace (Internet Gateway)
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: Innovatech-IGW

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref EKSVPC
      InternetGatewayId: !Ref InternetGateway

  # 3. SUBREDES PÚBLICAS
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref EKSVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: EKS-Public-Subnet-1
        - Key: kubernetes.io/role/elb
          Value: '1'

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref EKSVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: EKS-Public-Subnet-2
        - Key: kubernetes.io/role/elb
          Value: '1'

  # 4. TABLA DE ENRUTAMIENTO
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref EKSVPC
      Tags:
        - Key: Name
          Value: EKS-Public-RT

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  # Asociaciones de Ruta
  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

# 5. SALIDAS
Outputs:
  VpcId:
    Description: ID de la VPC Creada
    Value: !Ref EKSVPC
  PublicSubnets:
    Description: IDs de las Subredes Publicas
    Value: !Sub "${PublicSubnet1},${PublicSubnet2}"